---
- name: Install Free-IPA Client
  yum: name={{item}} state=present
  with_items:
    - ipa-client
    - ipa-admintools
    - httpd
    - mod_auth_kerb

- name: Configure Free-IPA Client
  command: "ipa-client-install --enable-dns-updates --ssh-trust-dns --domain={{ipa_domain}} --server={{kdc_fqdn}} -p admin -w {{password}} -U"
  notify:
    - reboot server