---
- name: Install Free-IPA Client
  yum: name={{item}} state=present
  with_items:
    - ipa-client
    - ipa-admintools
    - httpd
    - mod_auth_kerb

- name: Configure Free-IPA Client
  script: "configure_ipaclient.py -d {{ipa_domain}} -k {{kdc_fqdn}} -p {{password}}"
  notify: reboot sshd