---
- name: Install Free-IPA Server
  yum: name={{item}} state=present
  with_items:
    - bind
    - bind-dyndb-ldap
    - ipa-server

- name: Configure Free-IPA Server
  script: "configure_freeipa.py -f {{forwarder}} -r {{ipa_realm}} -h {{fqdn}} -d {{ipa_domain}} -p {{password}}"
  notify: reboot sshd