---
- name: Install Free-IPA Server
  yum: name={{item}} state=present
  with_items:
    - bind
    - bind-dyndb-ldap
    - ipa-server

- name: Configure Free-IPA Server
  command: "ipa-server-install --setup-dns --forwarder={{forwarder}} -r {{ipa_realm}} --hostname={{fqdn}} -n {{ipa_domain}} -a {{password}} -p {{password}} -U"
  # This is essential; without a reboot, kinit would not work.
  notify:
    - reboot server